@G:\Mahir\CSE302\LAB\banking.sql;

SELECT * FROM DEPOSITOR;

SELECT * FROM BORROWER;

SELECT * FROM ACCOUNT;

SELECT * FROM CUSTOMER;

SELECT * FROM BRANCH;

SELECT * FROM LOAN;

--TASK 01

SELECT BRANCH_NAME, BRANCH_CITY
FROM BRANCH
WHERE ASSETS>1000000;

--TASK 02

SELECT ACCOUNT_NUMBER, BALANCE
FROM ACCOUNT
WHERE BRANCH_NAME='DOWNTOWN' OR BALANCE BETWEEN 600 AND 750;

--TASK 03

SELECT ACCOUNT_NUMBER
FROM ACCOUNT NATURAL JOIN BRANCH
WHERE BRANCH_CITY='Rye';
        
--TASK 04

SELECT LOAN_NUMBER
FROM LOAN NATURAL JOIN BRANCH
WHERE AMOUNT>=1000 AND BRANCH_CITY='Harrison';

--TASK 05

SELECT *
FROM ACCOUNT
ORDER BY BALANCE DESC;

--TASK 06

SELECT *
FROM CUSTOMER
ORDER BY CUSTOMER_CITY;

--TASK 07

SELECT CUSTOMER_NAME
FROM DEPOSITOR
INTERSECT
SELECT CUSTOMER_NAME
FROM BORROWER;

--TASK 08

SELECT *
FROM CUSTOMER
WHERE CUSTOMER_NAME IN(
    SELECT CUSTOMER_NAME
    FROM DEPOSITOR
    UNION
    SELECT CUSTOMER_NAME
    FROM BORROWER);
    
--TASK 09

SELECT CUSTOMER_NAME
FROM CUSTOMER 
WHERE CUSTOMER_NAME IN(
    SELECT CUSTOMER_NAME
    FROM BORROWER
    MINUS
    SELECT CUSTOMER_NAME 
    FROM DEPOSITOR);
    
--TASK 10

SELECT SUM(ASSETS) AS TOTAL_ASSETS
FROM BRANCH;

--TASK 11

SELECT BRANCH_NAME,AVG(BALANCE) AS AVERAGE_BALANCE
FROM ACCOUNT
GROUP BY BRANCH_NAME;

--TASK 12

SELECT BRANCH_CITY,AVG(BALANCE) AS AVERAGE_BALANCE
FROM ACCOUNT NATURAL JOIN BRANCH
GROUP BY BRANCH_CITY;

--TASK 13

SELECT BRANCH_NAME, MIN(AMOUNT) AS LOWEST_AMOUNT
FROM LOAN 
GROUP BY BRANCH_NAME;

--TASK 14

SELECT BRANCH_NAME, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM LOAN 
GROUP BY BRANCH_NAME;

--TASK 15

SELECT CUSTOMER_NAME, ACCOUNT_NUMBER, BALANCE AS HIGHEST_BALANCE
FROM DEPOSITOR NATURAL JOIN ACCOUNT
WHERE BALANCE IN(
    SELECT MAX(BALANCE)
    FROM ACCOUNT);